version: "3.5"

services:
  postgres:
    image: postgres:9.6
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - programming_task
    volumes:
      - db-data:/var/lib/postgresql
    restart: always

  django:
    build:
      context: ./django
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_WAIT_TIMEOUT: ${DB_WAIT_TIMEOUT}
        DJANGO_PORT: ${DJANGO_PORT}
    env_file:
      - .env
    networks:
      - programming_task
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./django:/django
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      args:
        DJANGO_HOST: ${DJANGO_HOST}
        DJANGO_PORT: ${DJANGO_PORT}
        DJANGO_WAIT_TIMEOUT: ${DJANGO_WAIT_TIMEOUT}
    env_file:
      - .env
    networks:
      - programming_task
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - postgres
      - django

networks:
  programming_task:
    driver: bridge

volumes:
  db-data:
    driver: local
